(231015)
# Lab-01-1 Tensor Manipulation 1

In [1]:
import numpy as np
import torch

### 1D Array w/ NumPy

In [6]:
t = np.array([ 0., 1., 2., 3., 4., 5., 6. ])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [13]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  torch.Size([7])


In [8]:
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])  # Slicing
print(t[:2], t[3:])  # Slicing

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


### 2D Array w/ NumPy

In [10]:
t = np.array([[1., 2., 3.,], [4., 5., 6.,], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [32]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  2
Shape of t:  torch.Size([4, 3])


### 1D Array w/ PyTorch

In [12]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.,])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [14]:
print(t.dim())  # rank
print(t.shape)
print(t.size())  # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])


1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array w/ PyTorch

In [15]:
t = torch.FloatTensor([[1., 2., 3.,],
                      [4., 5., 6.,],
                      [7., 8., 9.,],
                      [10., 11., 12.,],
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [20]:
print(t.dim())
print(t.size())
print(t[:, 1])  # 1번째 차원에선 다 가져오고, 2번째 차원에서는 2번째 것만 가져와
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [52]:
# Same space
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

# 2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [56]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])  # (2, 2)
m2 = torch.FloatTensor([[1], [2]])  # (2, 1)
print(m1.shape, m2.shape)

# matlix multiplication
print(m1.matmul(m2))  # (2, 1)

# element-wise product (Hadamard product)
print(m1 * m2)  # (2, 2)
print(m1.mul(m2))  # ditto

torch.Size([2, 2]) torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean, Sum

In [59]:
t = torch.FloatTensor([1, 2])
print(t.mean())

# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)
    
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))  # dim=1 in here

tensor(1.5000)
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Max and Argmax

The `max` operator returns one value if it is called without an argument

In [71]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [70]:
print(t.max())

tensor(4.)


The `max` operator returns 2 values when called with dimension specified.

`(maximum value, argmax: the index of the element with maximum value)`

In [69]:
__max, __argmax = t.max(dim=0)
print("Max: ", __max)
print("Argmax: ", __argmax)

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
